spring.application.name=xxx

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GenderHealthCareSystem;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


jwt.base64-secret=DOxGF3ORUxD1oku6P8oUJgsG8DDWJ2rke9m4t8QR7Sit/NjKEv4TuFnD0/7koRZPQpCRyCohKY5dhc+X7nZ9rA==

validity-in-seconds=86400

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=genderhealthcarevn@gmail.com
spring.mail.password=zekguzqkgyizitef
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=duefuaxtx
cloudinary.api-key=864847846693864
cloudinary.api-secret=qpR1nv7dHJh1hoGW_-tz8cPsSCQ

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
## VNPay properties
#payment.vnPay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
#payment.vnPay.returnUrl=http://localhost:8080/payment/vn-pay-callback
#payment.vnPay.tmnCode=IGXBSMEO
#payment.vnPay.secretKey=HAMS4XOHN2TVP2O8454WXIUYPQEUFUSH
#payment.vnPay.version=2.1.0
#payment.vnPay.command=pay
#payment.vnPay.orderType=other
vnpay.tmnCode=IGXBSMEO
vnpay.hashSecret=HAMS4XOHN2TVP2O8454WXIUYPQEUFUSH
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://14.225.192.28/booking-result
spring.jackson.serialization.write-dates-as-timestamps=false
spring.security.oauth2.client.registration.google.redirect-uri=http://14.225.192.28/login/oauth2

spring.security.oauth2.client.registration.google.client-id=347670224849-qt76q3m77um1s3osobp4qo97b7eue2ia.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid, email, profile
paypal.client.id=ASL1u5BpHoA9YuWOEG_-hqCCGJpssrtzbnBYz3ug1B2tMxnjQds9Xu45eH8xLOwzNrE8Ys65TNslnZi7
paypal.client.secret=EF3hC2GqiqyaQPVJQUlAOlYN6KW1dQSxk30kQeet1XiMBGMtqfDT338hYN91KE1bPZLTA2i8mw7HQU9f
paypal.mode=sandbox
server.address=0.0.0.0
server.port=${PORT:8080}
